/*
	lateralOS 					(c) 2012 terraNova
	==============================================
	terraNova's leightweight Microkernel

	lateralOS - mmap.h
*/
#ifndef K_MMAP_H_
#define K_MMAP_H_

#include <lateralOS/types.h>

#define PAGE_ALIGNMENT	0x1000
#define ALIGN_UP(x)		(((x) + (PAGE_ALIGNMENT-1)) & ~(PAGE_ALIGNMENT-1))
#define ALIGN_DOWN(x)	((x) & ~(PAGE_ALIGNMENT-1))

extern uint KERNEL_START;
extern uint KERNEL_END;

#define MMAP_SIZE_VIDEO			(80*25*2)
#define MMAP_SIZE_PAGING		0x1000000 			// 1 mb
#define MMAP_SIZE_PMM			MMAP_SIZE_PAGING	// max size, nvm, its just an megabyte..

#define MMAP_SIZE_ALLOC			MMAP_VIRT_ALLOC_END - MMAP_VIRT_ALLOC_START

#define MMAP_PHYS_PAGING		ALIGN_UP((unsigned)(&KERNEL_END)) + PAGE_ALIGNMENT
#define MMAP_PHYS_PMM			MMAP_PHYS_PAGING + MMAP_SIZE_PAGING + PAGE_ALIGNMENT
#define MMAP_PHYS_VIDEO			0xb8000

#define MMAP_VIRT_KERNEL_START	0
#define MMAP_VIRT_KERNEL_END	0x10000000

#define MMAP_VIRT_USER_PAGING_START MMAP_VIRT_KERNEL_END
#define MMAP_VIRT_USER_PAGING_END	MMAP_SIZE_PAGING + MMAP_VIRT_USER_PAGING_START

#define MMAP_VIRT_USER_START 	MMAP_VIRT_USER_PAGING_END
#define MMAP_VIRT_USER_END		0x40000000

#define MMAP_VIRT_PAGING_START	MMAP_PHYS_PAGING
#define MMAP_VIRT_PAGING_END	MMAP_VIRT_PAGING_START + MMAP_SIZE_PAGING

#define MMAP_VIRT_VIDEO_START	MMAP_PHYS_VIDEO
#define MMAP_VIRT_VIDEO_END 	MMAP_VIRT_VIDEO_START + MMAP_SIZE_VIDEO

#define MMAP_VIRT_PMM_START		MMAP_PHYS_PMM
#define MMAP_VIRT_PMM_END		MMAP_VIRT_PMM_START + MMAP_SIZE_PMM

#define MMAP_VIRT_ALLOC_START	MMAP_VIRT_PMM_END
#define MMAP_VIRT_ALLOC_END		MMAP_VIRT_KERNEL_END

#endif /* K_MMAP_H_ */